<div class="dashicons-icon-action-3d-rotation" title="action-3d-rotation"></div>
<div class="dashicons-icon-action-accessibility" title="action-accessibility"></div>
<div class="dashicons-icon-action-account-balance" title="action-account-balance"></div>
<div class="dashicons-icon-action-account-balance-wallet" title="action-account-balance-wallet"></div>
<div class="dashicons-icon-action-account-box" title="action-account-box"></div>
<div class="dashicons-icon-action-account-child" title="action-account-child"></div>
<div class="dashicons-icon-action-account-circle" title="action-account-circle"></div>
<div class="dashicons-icon-action-add-shopping-cart" title="action-add-shopping-cart"></div>
<div class="dashicons-icon-action-alarm" title="action-alarm"></div>
<div class="dashicons-icon-action-alarm-add" title="action-alarm-add"></div>
<div class="dashicons-icon-action-alarm-off" title="action-alarm-off"></div>
<div class="dashicons-icon-action-alarm-on" title="action-alarm-on"></div>
<div class="dashicons-icon-action-android" title="action-android"></div>
<div class="dashicons-icon-action-announcement" title="action-announcement"></div>
<div class="dashicons-icon-action-aspect-ratio" title="action-aspect-ratio"></div>
<div class="dashicons-icon-action-assessment" title="action-assessment"></div>
<div class="dashicons-icon-action-assignment" title="action-assignment"></div>
<div class="dashicons-icon-action-assignment-ind" title="action-assignment-ind"></div>
<div class="dashicons-icon-action-assignment-late" title="action-assignment-late"></div>
<div class="dashicons-icon-action-assignment-return" title="action-assignment-return"></div>
<div class="dashicons-icon-action-assignment-returned" title="action-assignment-returned"></div>
<div class="dashicons-icon-action-assignment-turned-in" title="action-assignment-turned-in"></div>
<div class="dashicons-icon-action-autorenew" title="action-autorenew"></div>
<div class="dashicons-icon-action-backup" title="action-backup"></div>
<div class="dashicons-icon-action-book" title="action-book"></div>
<div class="dashicons-icon-action-bookmark" title="action-bookmark"></div>
<div class="dashicons-icon-action-bookmark-outline" title="action-bookmark-outline"></div>
<div class="dashicons-icon-action-bug-report" title="action-bug-report"></div>
<div class="dashicons-icon-action-cached" title="action-cached"></div>
<div class="dashicons-icon-action-class" title="action-class"></div>
<div class="dashicons-icon-action-credit-card" title="action-credit-card"></div>
<div class="dashicons-icon-action-dashboard" title="action-dashboard"></div>
<div class="dashicons-icon-action-delete" title="action-delete"></div>
<div class="dashicons-icon-action-description" title="action-description"></div>
<div class="dashicons-icon-action-dns" title="action-dns"></div>
<div class="dashicons-icon-action-done" title="action-done"></div>
<div class="dashicons-icon-action-done-all" title="action-done-all"></div>
<div class="dashicons-icon-action-event" title="action-event"></div>
<div class="dashicons-icon-action-exit-to-app" title="action-exit-to-app"></div>
<div class="dashicons-icon-action-explore" title="action-explore"></div>
<div class="dashicons-icon-action-extension" title="action-extension"></div>
<div class="dashicons-icon-action-face-unlock" title="action-face-unlock"></div>
<div class="dashicons-icon-action-favorite" title="action-favorite"></div>
<div class="dashicons-icon-action-favorite-outline" title="action-favorite-outline"></div>
<div class="dashicons-icon-action-find-in-page" title="action-find-in-page"></div>
<div class="dashicons-icon-action-find-replace" title="action-find-replace"></div>
<div class="dashicons-icon-action-flip-to-back" title="action-flip-to-back"></div>
<div class="dashicons-icon-action-flip-to-front" title="action-flip-to-front"></div>
<div class="dashicons-icon-action-get-app" title="action-get-app"></div>
<div class="dashicons-icon-action-grade" title="action-grade"></div>
<div class="dashicons-icon-action-group-work" title="action-group-work"></div>
<div class="dashicons-icon-action-help" title="action-help"></div>
<div class="dashicons-icon-action-highlight-remove" title="action-highlight-remove"></div>
<div class="dashicons-icon-action-history" title="action-history"></div>
<div class="dashicons-icon-action-home" title="action-home"></div>
<div class="dashicons-icon-action-https" title="action-https"></div>
<div class="dashicons-icon-action-info" title="action-info"></div>
<div class="dashicons-icon-action-info-outline" title="action-info-outline"></div>
<div class="dashicons-icon-action-input" title="action-input"></div>
<div class="dashicons-icon-action-invert-colors" title="action-invert-colors"></div>
<div class="dashicons-icon-action-label" title="action-label"></div>
<div class="dashicons-icon-action-label-outline" title="action-label-outline"></div>
<div class="dashicons-icon-action-language" title="action-language"></div>
<div class="dashicons-icon-action-launch" title="action-launch"></div>
<div class="dashicons-icon-action-list" title="action-list"></div>
<div class="dashicons-icon-action-lock" title="action-lock"></div>
<div class="dashicons-icon-action-lock-open" title="action-lock-open"></div>
<div class="dashicons-icon-action-lock-outline" title="action-lock-outline"></div>
<div class="dashicons-icon-action-loyalty" title="action-loyalty"></div>
<div class="dashicons-icon-action-markunread-mailbox" title="action-markunread-mailbox"></div>
<div class="dashicons-icon-action-note-add" title="action-note-add"></div>
<div class="dashicons-icon-action-open-in-browser" title="action-open-in-browser"></div>
<div class="dashicons-icon-action-open-in-new" title="action-open-in-new"></div>
<div class="dashicons-icon-action-open-with" title="action-open-with"></div>
<div class="dashicons-icon-action-pageview" title="action-pageview"></div>
<div class="dashicons-icon-action-payment" title="action-payment"></div>
<div class="dashicons-icon-action-perm-camera-mic" title="action-perm-camera-mic"></div>
<div class="dashicons-icon-action-perm-contact-cal" title="action-perm-contact-cal"></div>
<div class="dashicons-icon-action-perm-data-setting" title="action-perm-data-setting"></div>
<div class="dashicons-icon-action-perm-device-info" title="action-perm-device-info"></div>
<div class="dashicons-icon-action-perm-identity" title="action-perm-identity"></div>
<div class="dashicons-icon-action-perm-media" title="action-perm-media"></div>
<div class="dashicons-icon-action-perm-phone-msg" title="action-perm-phone-msg"></div>
<div class="dashicons-icon-action-perm-scan-wifi" title="action-perm-scan-wifi"></div>
<div class="dashicons-icon-action-picture-in-picture" title="action-picture-in-picture"></div>
<div class="dashicons-icon-action-polymer" title="action-polymer"></div>
<div class="dashicons-icon-action-print" title="action-print"></div>
<div class="dashicons-icon-action-query-builder" title="action-query-builder"></div>
<div class="dashicons-icon-action-question-answer" title="action-question-answer"></div>
<div class="dashicons-icon-action-receipt" title="action-receipt"></div>
<div class="dashicons-icon-action-redeem" title="action-redeem"></div>
<div class="dashicons-icon-action-report-problem" title="action-report-problem"></div>
<div class="dashicons-icon-action-restore" title="action-restore"></div>
<div class="dashicons-icon-action-room" title="action-room"></div>
<div class="dashicons-icon-action-schedule" title="action-schedule"></div>
<div class="dashicons-icon-action-search" title="action-search"></div>
<div class="dashicons-icon-action-settings" title="action-settings"></div>
<div class="dashicons-icon-action-settings-applications" title="action-settings-applications"></div>
<div class="dashicons-icon-action-settings-backup-restore" title="action-settings-backup-restore"></div>
<div class="dashicons-icon-action-settings-bluetooth" title="action-settings-bluetooth"></div>
<div class="dashicons-icon-action-settings-cell" title="action-settings-cell"></div>
<div class="dashicons-icon-action-settings-display" title="action-settings-display"></div>
<div class="dashicons-icon-action-settings-ethernet" title="action-settings-ethernet"></div>
<div class="dashicons-icon-action-settings-input-antenna" title="action-settings-input-antenna"></div>
<div class="dashicons-icon-action-settings-input-component" title="action-settings-input-component"></div>
<div class="dashicons-icon-action-settings-input-composite" title="action-settings-input-composite"></div>
<div class="dashicons-icon-action-settings-input-hdmi" title="action-settings-input-hdmi"></div>
<div class="dashicons-icon-action-settings-input-svideo" title="action-settings-input-svideo"></div>
<div class="dashicons-icon-action-settings-overscan" title="action-settings-overscan"></div>
<div class="dashicons-icon-action-settings-phone" title="action-settings-phone"></div>
<div class="dashicons-icon-action-settings-power" title="action-settings-power"></div>
<div class="dashicons-icon-action-settings-remote" title="action-settings-remote"></div>
<div class="dashicons-icon-action-settings-voice" title="action-settings-voice"></div>
<div class="dashicons-icon-action-shop" title="action-shop"></div>
<div class="dashicons-icon-action-shop-two" title="action-shop-two"></div>
<div class="dashicons-icon-action-shopping-basket" title="action-shopping-basket"></div>
<div class="dashicons-icon-action-shopping-cart" title="action-shopping-cart"></div>
<div class="dashicons-icon-action-speaker-notes" title="action-speaker-notes"></div>
<div class="dashicons-icon-action-spellcheck" title="action-spellcheck"></div>
<div class="dashicons-icon-action-star-rate" title="action-star-rate"></div>
<div class="dashicons-icon-action-stars" title="action-stars"></div>
<div class="dashicons-icon-action-store" title="action-store"></div>
<div class="dashicons-icon-action-subject" title="action-subject"></div>
<div class="dashicons-icon-action-swap-horiz" title="action-swap-horiz"></div>
<div class="dashicons-icon-action-swap-vert" title="action-swap-vert"></div>
<div class="dashicons-icon-action-swap-vert-circle" title="action-swap-vert-circle"></div>
<div class="dashicons-icon-action-system-update-tv" title="action-system-update-tv"></div>
<div class="dashicons-icon-action-tab" title="action-tab"></div>
<div class="dashicons-icon-action-tab-unselected" title="action-tab-unselected"></div>
<div class="dashicons-icon-action-theaters" title="action-theaters"></div>
<div class="dashicons-icon-action-thumb-down" title="action-thumb-down"></div>
<div class="dashicons-icon-action-thumb-up" title="action-thumb-up"></div>
<div class="dashicons-icon-action-thumbs-up-down" title="action-thumbs-up-down"></div>
<div class="dashicons-icon-action-toc" title="action-toc"></div>
<div class="dashicons-icon-action-today" title="action-today"></div>
<div class="dashicons-icon-action-track-changes" title="action-track-changes"></div>
<div class="dashicons-icon-action-translate" title="action-translate"></div>
<div class="dashicons-icon-action-trending-down" title="action-trending-down"></div>
<div class="dashicons-icon-action-trending-neutral" title="action-trending-neutral"></div>
<div class="dashicons-icon-action-trending-up" title="action-trending-up"></div>
<div class="dashicons-icon-action-turned-in" title="action-turned-in"></div>
<div class="dashicons-icon-action-turned-in-not" title="action-turned-in-not"></div>
<div class="dashicons-icon-action-verified-user" title="action-verified-user"></div>
<div class="dashicons-icon-action-view-agenda" title="action-view-agenda"></div>
<div class="dashicons-icon-action-view-array" title="action-view-array"></div>
<div class="dashicons-icon-action-view-carousel" title="action-view-carousel"></div>
<div class="dashicons-icon-action-view-column" title="action-view-column"></div>
<div class="dashicons-icon-action-view-day" title="action-view-day"></div>
<div class="dashicons-icon-action-view-headline" title="action-view-headline"></div>
<div class="dashicons-icon-action-view-list" title="action-view-list"></div>
<div class="dashicons-icon-action-view-module" title="action-view-module"></div>
<div class="dashicons-icon-action-view-quilt" title="action-view-quilt"></div>
<div class="dashicons-icon-action-view-stream" title="action-view-stream"></div>
<div class="dashicons-icon-action-view-week" title="action-view-week"></div>
<div class="dashicons-icon-action-visibility" title="action-visibility"></div>
<div class="dashicons-icon-action-visibility-off" title="action-visibility-off"></div>
<div class="dashicons-icon-action-wallet-giftcard" title="action-wallet-giftcard"></div>
<div class="dashicons-icon-action-wallet-membership" title="action-wallet-membership"></div>
<div class="dashicons-icon-action-wallet-travel" title="action-wallet-travel"></div>
<div class="dashicons-icon-action-work" title="action-work"></div>

<div class="dashicons-icon-av-album" title="av-album"></div>
<div class="dashicons-icon-av-timer" title="av-timer"></div>
<div class="dashicons-icon-av-closed-caption" title="av-closed-caption"></div>
<div class="dashicons-icon-av-equalizer" title="av-equalizer"></div>
<div class="dashicons-icon-av-explicit" title="av-explicit"></div>
<div class="dashicons-icon-av-fast-forward" title="av-fast-forward"></div>
<div class="dashicons-icon-av-fast-rewind" title="av-fast-rewind"></div>
<div class="dashicons-icon-av-games" title="av-games"></div>
<div class="dashicons-icon-av-hearing" title="av-hearing"></div>
<div class="dashicons-icon-av-high-quality" title="av-high-quality"></div>
<div class="dashicons-icon-av-loop" title="av-loop"></div>
<div class="dashicons-icon-av-mic" title="av-mic"></div>
<div class="dashicons-icon-av-mic-none" title="av-mic-none"></div>
<div class="dashicons-icon-av-mic-off" title="av-mic-off"></div>
<div class="dashicons-icon-av-movie" title="av-movie"></div>
<div class="dashicons-icon-av-my-library-add" title="av-my-library-add"></div>
<div class="dashicons-icon-av-my-library-books" title="av-my-library-books"></div>
<div class="dashicons-icon-av-my-library-music" title="av-my-library-music"></div>
<div class="dashicons-icon-av-new-releases" title="av-new-releases"></div>
<div class="dashicons-icon-av-not-interested" title="av-not-interested"></div>
<div class="dashicons-icon-av-pause" title="av-pause"></div>
<div class="dashicons-icon-av-pause-circle-fill" title="av-pause-circle-fill"></div>
<div class="dashicons-icon-av-pause-circle-outline" title="av-pause-circle-outline"></div>
<div class="dashicons-icon-av-play-arrow" title="av-play-arrow"></div>
<div class="dashicons-icon-av-play-circle-fill" title="av-play-circle-fill"></div>
<div class="dashicons-icon-av-play-circle-outline" title="av-play-circle-outline"></div>
<div class="dashicons-icon-av-play-shopping-bag" title="av-play-shopping-bag"></div>
<div class="dashicons-icon-av-playlist-add" title="av-playlist-add"></div>
<div class="dashicons-icon-av-queue" title="av-queue"></div>
<div class="dashicons-icon-av-queue-music" title="av-queue-music"></div>
<div class="dashicons-icon-av-radio" title="av-radio"></div>
<div class="dashicons-icon-av-recent-actors" title="av-recent-actors"></div>
<div class="dashicons-icon-av-repeat" title="av-repeat"></div>
<div class="dashicons-icon-av-repeat-one" title="av-repeat-one"></div>
<div class="dashicons-icon-av-replay" title="av-replay"></div>
<div class="dashicons-icon-av-shuffle" title="av-shuffle"></div>
<div class="dashicons-icon-av-skip-next" title="av-skip-next"></div>
<div class="dashicons-icon-av-skip-previous" title="av-skip-previous"></div>
<div class="dashicons-icon-av-snooze" title="av-snooze"></div>
<div class="dashicons-icon-av-stop" title="av-stop"></div>
<div class="dashicons-icon-av-subtitles" title="av-subtitles"></div>
<div class="dashicons-icon-av-surround-sound" title="av-surround-sound"></div>
<div class="dashicons-icon-av-video-collection" title="av-video-collection"></div>
<div class="dashicons-icon-av-videocam" title="av-videocam"></div>
<div class="dashicons-icon-av-videocam-off" title="av-videocam-off"></div>
<div class="dashicons-icon-av-volume-down" title="av-volume-down"></div>
<div class="dashicons-icon-av-volume-mute" title="av-volume-mute"></div>
<div class="dashicons-icon-av-volume-off" title="av-volume-off"></div>
<div class="dashicons-icon-av-volume-up" title="av-volume-up"></div>
<div class="dashicons-icon-av-web" title="av-web"></div>

<div class="dashicons-icon-communication-business" title="communication-business"></div>
<div class="dashicons-icon-communication-call" title="communication-call"></div>
<div class="dashicons-icon-communication-call-end" title="communication-call-end"></div>
<div class="dashicons-icon-communication-call-made" title="communication-call-made"></div>
<div class="dashicons-icon-communication-call-merge" title="communication-call-merge"></div>
<div class="dashicons-icon-communication-call-missed" title="communication-call-missed"></div>
<div class="dashicons-icon-communication-call-received" title="communication-call-received"></div>
<div class="dashicons-icon-communication-call-split" title="communication-call-split"></div>
<div class="dashicons-icon-communication-chat" title="communication-chat"></div>
<div class="dashicons-icon-communication-clear-all" title="communication-clear-all"></div>
<div class="dashicons-icon-communication-comment" title="communication-comment"></div>
<div class="dashicons-icon-communication-contacts" title="communication-contacts"></div>
<div class="dashicons-icon-communication-dialer-sip" title="communication-dialer-sip"></div>
<div class="dashicons-icon-communication-dialpad" title="communication-dialpad"></div>
<div class="dashicons-icon-communication-dnd-on" title="communication-dnd-on"></div>
<div class="dashicons-icon-communication-email" title="communication-email"></div>
<div class="dashicons-icon-communication-forum" title="communication-forum"></div>
<div class="dashicons-icon-communication-import-export" title="communication-import-export"></div>
<div class="dashicons-icon-communication-invert-colors-off" title="communication-invert-colors-off"></div>
<div class="dashicons-icon-communication-invert-colors-on" title="communication-invert-colors-on"></div>
<div class="dashicons-icon-communication-live-help" title="communication-live-help"></div>
<div class="dashicons-icon-communication-location-off" title="communication-location-off"></div>
<div class="dashicons-icon-communication-location-on" title="communication-location-on"></div>
<div class="dashicons-icon-communication-message" title="communication-message"></div>
<div class="dashicons-icon-communication-messenger" title="communication-messenger"></div>
<div class="dashicons-icon-communication-no-sim" title="communication-no-sim"></div>
<div class="dashicons-icon-communication-phone" title="communication-phone"></div>
<div class="dashicons-icon-communication-portable-wifi-off" title="communication-portable-wifi-off"></div>
<div class="dashicons-icon-communication-quick-contacts-dialer" title="communication-quick-contacts-dialer"></div>
<div class="dashicons-icon-communication-quick-contacts-mail" title="communication-quick-contacts-mail"></div>
<div class="dashicons-icon-communication-ring-volume" title="communication-ring-volume"></div>
<div class="dashicons-icon-communication-stay-current-landscape" title="communication-stay-current-landscape"></div>
<div class="dashicons-icon-communication-stay-current-portrait" title="communication-stay-current-portrait"></div>
<div class="dashicons-icon-communication-stay-primary-landscape" title="communication-stay-primary-landscape"></div>
<div class="dashicons-icon-communication-stay-primary-portrait" title="communication-stay-primary-portrait"></div>
<div class="dashicons-icon-communication-swap-calls" title="communication-swap-calls"></div>
<div class="dashicons-icon-communication-textsms" title="communication-textsms"></div>
<div class="dashicons-icon-communication-voicemail" title="communication-voicemail"></div>
<div class="dashicons-icon-communication-vpn-key" title="communication-vpn-key"></div>

<div class="dashicons-icon-content-add" title="content-add"></div>
<div class="dashicons-icon-content-add-box" title="content-add-box"></div>
<div class="dashicons-icon-content-add-circle" title="content-add-circle"></div>
<div class="dashicons-icon-content-add-circle-outline" title="content-add-circle-outline"></div>
<div class="dashicons-icon-content-archive" title="content-archive"></div>
<div class="dashicons-icon-content-backspace" title="content-backspace"></div>
<div class="dashicons-icon-content-block" title="content-block"></div>
<div class="dashicons-icon-content-clear" title="content-clear"></div>
<div class="dashicons-icon-content-content-copy" title="content-content-copy"></div>
<div class="dashicons-icon-content-content-cut" title="content-content-cut"></div>
<div class="dashicons-icon-content-content-paste" title="content-content-paste"></div>
<div class="dashicons-icon-content-create" title="content-create"></div>
<div class="dashicons-icon-content-drafts" title="content-drafts"></div>
<div class="dashicons-icon-content-filter-list" title="content-filter-list"></div>
<div class="dashicons-icon-content-flag" title="content-flag"></div>
<div class="dashicons-icon-content-forward" title="content-forward"></div>
<div class="dashicons-icon-content-gesture" title="content-gesture"></div>
<div class="dashicons-icon-content-inbox" title="content-inbox"></div>
<div class="dashicons-icon-content-link" title="content-link"></div>
<div class="dashicons-icon-content-mail" title="content-mail"></div>
<div class="dashicons-icon-content-markunread" title="content-markunread"></div>
<div class="dashicons-icon-content-redo" title="content-redo"></div>
<div class="dashicons-icon-content-remove" title="content-remove"></div>
<div class="dashicons-icon-content-remove-circle" title="content-remove-circle"></div>
<div class="dashicons-icon-content-remove-circle-outline" title="content-remove-circle-outline"></div>
<div class="dashicons-icon-content-reply" title="content-reply"></div>
<div class="dashicons-icon-content-reply-all" title="content-reply-all"></div>
<div class="dashicons-icon-content-report" title="content-report"></div>
<div class="dashicons-icon-content-save" title="content-save"></div>
<div class="dashicons-icon-content-select-all" title="content-select-all"></div>
<div class="dashicons-icon-content-send" title="content-send"></div>
<div class="dashicons-icon-content-sort" title="content-sort"></div>
<div class="dashicons-icon-content-text-format" title="content-text-format"></div>
<div class="dashicons-icon-content-undo" title="content-undo"></div>

<div class="dashicons-icon-device-access-alarm" title="device-access-alarm"></div>
<div class="dashicons-icon-device-access-alarms" title="device-access-alarms"></div>
<div class="dashicons-icon-device-access-time" title="device-access-time"></div>
<div class="dashicons-icon-device-add-alarm" title="device-add-alarm"></div>
<div class="dashicons-icon-device-airplanemode-off" title="device-airplanemode-off"></div>
<div class="dashicons-icon-device-airplanemode-on" title="device-airplanemode-on"></div>
<div class="dashicons-icon-device-battery-20" title="device-battery-20"></div>
<div class="dashicons-icon-device-battery-30" title="device-battery-30"></div>
<div class="dashicons-icon-device-battery-50" title="device-battery-50"></div>
<div class="dashicons-icon-device-battery-60" title="device-battery-60"></div>
<div class="dashicons-icon-device-battery-80" title="device-battery-80"></div>
<div class="dashicons-icon-device-battery-90" title="device-battery-90"></div>
<div class="dashicons-icon-device-battery-alert" title="device-battery-alert"></div>
<div class="dashicons-icon-device-battery-charging-20" title="device-battery-charging-20"></div>
<div class="dashicons-icon-device-battery-charging-30" title="device-battery-charging-30"></div>
<div class="dashicons-icon-device-battery-charging-50" title="device-battery-charging-50"></div>
<div class="dashicons-icon-device-battery-charging-60" title="device-battery-charging-60"></div>
<div class="dashicons-icon-device-battery-charging-80" title="device-battery-charging-80"></div>
<div class="dashicons-icon-device-battery-charging-90" title="device-battery-charging-90"></div>
<div class="dashicons-icon-device-battery-charging-full" title="device-battery-charging-full"></div>
<div class="dashicons-icon-device-battery-full" title="device-battery-full"></div>
<div class="dashicons-icon-device-battery-std" title="device-battery-std"></div>
<div class="dashicons-icon-device-battery-unknown" title="device-battery-unknown"></div>
<div class="dashicons-icon-device-bluetooth" title="device-bluetooth"></div>
<div class="dashicons-icon-device-bluetooth-connected" title="device-bluetooth-connected"></div>
<div class="dashicons-icon-device-bluetooth-disabled" title="device-bluetooth-disabled"></div>
<div class="dashicons-icon-device-bluetooth-searching" title="device-bluetooth-searching"></div>
<div class="dashicons-icon-device-brightness-auto" title="device-brightness-auto"></div>
<div class="dashicons-icon-device-brightness-high" title="device-brightness-high"></div>
<div class="dashicons-icon-device-brightness-low" title="device-brightness-low"></div>
<div class="dashicons-icon-device-brightness-medium" title="device-brightness-medium"></div>
<div class="dashicons-icon-device-data-usage" title="device-data-usage"></div>
<div class="dashicons-icon-device-developer-mode" title="device-developer-mode"></div>
<div class="dashicons-icon-device-devices" title="device-devices"></div>
<div class="dashicons-icon-device-dvr" title="device-dvr"></div>
<div class="dashicons-icon-device-gps-fixed" title="device-gps-fixed"></div>
<div class="dashicons-icon-device-gps-not-fixed" title="device-gps-not-fixed"></div>
<div class="dashicons-icon-device-gps-off" title="device-gps-off"></div>
<div class="dashicons-icon-device-location-disabled" title="device-location-disabled"></div>
<div class="dashicons-icon-device-location-searching" title="device-location-searching"></div>
<div class="dashicons-icon-device-multitrack-audio" title="device-multitrack-audio"></div>
<div class="dashicons-icon-device-network-cell" title="device-network-cell"></div>
<div class="dashicons-icon-device-network-wifi" title="device-network-wifi"></div>
<div class="dashicons-icon-device-nfc" title="device-nfc"></div>
<div class="dashicons-icon-device-now-wallpaper" title="device-now-wallpaper"></div>
<div class="dashicons-icon-device-now-widgets" title="device-now-widgets"></div>
<div class="dashicons-icon-device-screen-lock-landscape" title="device-screen-lock-landscape"></div>
<div class="dashicons-icon-device-screen-lock-portrait" title="device-screen-lock-portrait"></div>
<div class="dashicons-icon-device-screen-lock-rotation" title="device-screen-lock-rotation"></div>
<div class="dashicons-icon-device-screen-rotation" title="device-screen-rotation"></div>
<div class="dashicons-icon-device-sd-storage" title="device-sd-storage"></div>
<div class="dashicons-icon-device-settings-system-daydream" title="device-settings-system-daydream"></div>
<div class="dashicons-icon-device-signal-cellular-0-bar" title="device-signal-cellular-0-bar"></div>
<div class="dashicons-icon-device-signal-cellular-1-bar" title="device-signal-cellular-1-bar"></div>
<div class="dashicons-icon-device-signal-cellular-2-bar" title="device-signal-cellular-2-bar"></div>
<div class="dashicons-icon-device-signal-cellular-3-bar" title="device-signal-cellular-3-bar"></div>
<div class="dashicons-icon-device-signal-cellular-4-bar" title="device-signal-cellular-4-bar"></div>
<div class="dashicons-icon-device-signal-cellular-connected-no-internet-0-bar" title="device-signal-cellular-connected-no-internet-0-bar"></div>
<div class="dashicons-icon-device-signal-cellular-connected-no-internet-1-bar" title="device-signal-cellular-connected-no-internet-1-bar"></div>
<div class="dashicons-icon-device-signal-cellular-connected-no-internet-2-bar" title="device-signal-cellular-connected-no-internet-2-bar"></div>
<div class="dashicons-icon-device-signal-cellular-connected-no-internet-3-bar" title="device-signal-cellular-connected-no-internet-3-bar"></div>
<div class="dashicons-icon-device-signal-cellular-connected-no-internet-4-bar" title="device-signal-cellular-connected-no-internet-4-bar"></div>
<div class="dashicons-icon-device-signal-cellular-no-sim" title="device-signal-cellular-no-sim"></div>
<div class="dashicons-icon-device-signal-cellular-null" title="device-signal-cellular-null"></div>
<div class="dashicons-icon-device-signal-cellular-off" title="device-signal-cellular-off"></div>
<div class="dashicons-icon-device-signal-wifi-0-bar" title="device-signal-wifi-0-bar"></div>
<div class="dashicons-icon-device-signal-wifi-1-bar" title="device-signal-wifi-1-bar"></div>
<div class="dashicons-icon-device-signal-wifi-2-bar" title="device-signal-wifi-2-bar"></div>
<div class="dashicons-icon-device-signal-wifi-3-bar" title="device-signal-wifi-3-bar"></div>
<div class="dashicons-icon-device-signal-wifi-4-bar" title="device-signal-wifi-4-bar"></div>
<div class="dashicons-icon-device-signal-wifi-off" title="device-signal-wifi-off"></div>
<div class="dashicons-icon-device-storage" title="device-storage"></div>
<div class="dashicons-icon-device-usb" title="device-usb"></div>
<div class="dashicons-icon-device-wifi-lock" title="device-wifi-lock"></div>
<div class="dashicons-icon-device-wifi-tethering" title="device-wifi-tethering"></div>

<div class="dashicons-icon-editor-attach-file" title="editor-attach-file"></div>
<div class="dashicons-icon-editor-attach-money" title="editor-attach-money"></div>
<div class="dashicons-icon-editor-border-all" title="editor-border-all"></div>
<div class="dashicons-icon-editor-border-bottom" title="editor-border-bottom"></div>
<div class="dashicons-icon-editor-border-clear" title="editor-border-clear"></div>
<div class="dashicons-icon-editor-border-color" title="editor-border-color"></div>
<div class="dashicons-icon-editor-border-horizontal" title="editor-border-horizontal"></div>
<div class="dashicons-icon-editor-border-inner" title="editor-border-inner"></div>
<div class="dashicons-icon-editor-border-left" title="editor-border-left"></div>
<div class="dashicons-icon-editor-border-outer" title="editor-border-outer"></div>
<div class="dashicons-icon-editor-border-right" title="editor-border-right"></div>
<div class="dashicons-icon-editor-border-style" title="editor-border-style"></div>
<div class="dashicons-icon-editor-border-top" title="editor-border-top"></div>
<div class="dashicons-icon-editor-border-vertical" title="editor-border-vertical"></div>
<div class="dashicons-icon-editor-format-align-center" title="editor-format-align-center"></div>
<div class="dashicons-icon-editor-format-align-justify" title="editor-format-align-justify"></div>
<div class="dashicons-icon-editor-format-align-left" title="editor-format-align-left"></div>
<div class="dashicons-icon-editor-format-align-right" title="editor-format-align-right"></div>
<div class="dashicons-icon-editor-format-bold" title="editor-format-bold"></div>
<div class="dashicons-icon-editor-format-clear" title="editor-format-clear"></div>
<div class="dashicons-icon-editor-format-color-fill" title="editor-format-color-fill"></div>
<div class="dashicons-icon-editor-format-color-reset" title="editor-format-color-reset"></div>
<div class="dashicons-icon-editor-format-color-text" title="editor-format-color-text"></div>
<div class="dashicons-icon-editor-format-indent-decrease" title="editor-format-indent-decrease"></div>
<div class="dashicons-icon-editor-format-indent-increase" title="editor-format-indent-increase"></div>
<div class="dashicons-icon-editor-format-italic" title="editor-format-italic"></div>
<div class="dashicons-icon-editor-format-line-spacing" title="editor-format-line-spacing"></div>
<div class="dashicons-icon-editor-format-list-bulleted" title="editor-format-list-bulleted"></div>
<div class="dashicons-icon-editor-format-list-numbered" title="editor-format-list-numbered"></div>
<div class="dashicons-icon-editor-format-paint" title="editor-format-paint"></div>
<div class="dashicons-icon-editor-format-quote" title="editor-format-quote"></div>
<div class="dashicons-icon-editor-format-size" title="editor-format-size"></div>
<div class="dashicons-icon-editor-format-strikethrough" title="editor-format-strikethrough"></div>
<div class="dashicons-icon-editor-format-textdirection-l-to-r" title="editor-format-textdirection-l-to-r"></div>
<div class="dashicons-icon-editor-format-textdirection-r-to-l" title="editor-format-textdirection-r-to-l"></div>
<div class="dashicons-icon-editor-format-underline" title="editor-format-underline"></div>
<div class="dashicons-icon-editor-functions" title="editor-functions"></div>
<div class="dashicons-icon-editor-insert-chart" title="editor-insert-chart"></div>
<div class="dashicons-icon-editor-insert-comment" title="editor-insert-comment"></div>
<div class="dashicons-icon-editor-insert-drive-file" title="editor-insert-drive-file"></div>
<div class="dashicons-icon-editor-insert-emoticon" title="editor-insert-emoticon"></div>
<div class="dashicons-icon-editor-insert-invitation" title="editor-insert-invitation"></div>
<div class="dashicons-icon-editor-insert-link" title="editor-insert-link"></div>
<div class="dashicons-icon-editor-insert-photo" title="editor-insert-photo"></div>
<div class="dashicons-icon-editor-merge-type" title="editor-merge-type"></div>
<div class="dashicons-icon-editor-mode-comment" title="editor-mode-comment"></div>
<div class="dashicons-icon-editor-mode-edit" title="editor-mode-edit"></div>
<div class="dashicons-icon-editor-publish" title="editor-publish"></div>
<div class="dashicons-icon-editor-vertical-align-bottom" title="editor-vertical-align-bottom"></div>
<div class="dashicons-icon-editor-vertical-align-center" title="editor-vertical-align-center"></div>
<div class="dashicons-icon-editor-vertical-align-top" title="editor-vertical-align-top"></div>
<div class="dashicons-icon-editor-wrap-text" title="editor-wrap-text"></div>

<div class="dashicons-icon-file-attachment" title="file-attachment"></div>
<div class="dashicons-icon-file-cloud" title="file-cloud"></div>
<div class="dashicons-icon-file-cloud-circle" title="file-cloud-circle"></div>
<div class="dashicons-icon-file-cloud-done" title="file-cloud-done"></div>
<div class="dashicons-icon-file-cloud-download" title="file-cloud-download"></div>
<div class="dashicons-icon-file-cloud-off" title="file-cloud-off"></div>
<div class="dashicons-icon-file-cloud-queue" title="file-cloud-queue"></div>
<div class="dashicons-icon-file-cloud-upload" title="file-cloud-upload"></div>
<div class="dashicons-icon-file-file-download" title="file-file-download"></div>
<div class="dashicons-icon-file-file-upload" title="file-file-upload"></div>
<div class="dashicons-icon-file-folder" title="file-folder"></div>
<div class="dashicons-icon-file-folder-open" title="file-folder-open"></div>
<div class="dashicons-icon-file-folder-shared" title="file-folder-shared"></div>

<div class="dashicons-icon-hardware-cast" title="hardware-cast"></div>
<div class="dashicons-icon-hardware-cast-connected" title="hardware-cast-connected"></div>
<div class="dashicons-icon-hardware-computer" title="hardware-computer"></div>
<div class="dashicons-icon-hardware-desktop-mac" title="hardware-desktop-mac"></div>
<div class="dashicons-icon-hardware-desktop-windows" title="hardware-desktop-windows"></div>
<div class="dashicons-icon-hardware-dock" title="hardware-dock"></div>
<div class="dashicons-icon-hardware-gamepad" title="hardware-gamepad"></div>
<div class="dashicons-icon-hardware-headset" title="hardware-headset"></div>
<div class="dashicons-icon-hardware-headset-mic" title="hardware-headset-mic"></div>
<div class="dashicons-icon-hardware-keyboard" title="hardware-keyboard"></div>
<div class="dashicons-icon-hardware-keyboard-alt" title="hardware-keyboard-alt"></div>
<div class="dashicons-icon-hardware-keyboard-arrow-down" title="hardware-keyboard-arrow-down"></div>
<div class="dashicons-icon-hardware-keyboard-arrow-left" title="hardware-keyboard-arrow-left"></div>
<div class="dashicons-icon-hardware-keyboard-arrow-right" title="hardware-keyboard-arrow-right"></div>
<div class="dashicons-icon-hardware-keyboard-arrow-up" title="hardware-keyboard-arrow-up"></div>
<div class="dashicons-icon-hardware-keyboard-backspace" title="hardware-keyboard-backspace"></div>
<div class="dashicons-icon-hardware-keyboard-capslock" title="hardware-keyboard-capslock"></div>
<div class="dashicons-icon-hardware-keyboard-control" title="hardware-keyboard-control"></div>
<div class="dashicons-icon-hardware-keyboard-hide" title="hardware-keyboard-hide"></div>
<div class="dashicons-icon-hardware-keyboard-return" title="hardware-keyboard-return"></div>
<div class="dashicons-icon-hardware-keyboard-tab" title="hardware-keyboard-tab"></div>
<div class="dashicons-icon-hardware-keyboard-voice" title="hardware-keyboard-voice"></div>
<div class="dashicons-icon-hardware-laptop" title="hardware-laptop"></div>
<div class="dashicons-icon-hardware-laptop-chromebook" title="hardware-laptop-chromebook"></div>
<div class="dashicons-icon-hardware-laptop-mac" title="hardware-laptop-mac"></div>
<div class="dashicons-icon-hardware-laptop-windows" title="hardware-laptop-windows"></div>
<div class="dashicons-icon-hardware-memory" title="hardware-memory"></div>
<div class="dashicons-icon-hardware-mouse" title="hardware-mouse"></div>
<div class="dashicons-icon-hardware-phone-android" title="hardware-phone-android"></div>
<div class="dashicons-icon-hardware-phone-iphone" title="hardware-phone-iphone"></div>
<div class="dashicons-icon-hardware-phonelink" title="hardware-phonelink"></div>
<div class="dashicons-icon-hardware-phonelink-off" title="hardware-phonelink-off"></div>
<div class="dashicons-icon-hardware-security" title="hardware-security"></div>
<div class="dashicons-icon-hardware-sim-card" title="hardware-sim-card"></div>
<div class="dashicons-icon-hardware-smartphone" title="hardware-smartphone"></div>
<div class="dashicons-icon-hardware-speaker" title="hardware-speaker"></div>
<div class="dashicons-icon-hardware-tablet" title="hardware-tablet"></div>
<div class="dashicons-icon-hardware-tablet-android" title="hardware-tablet-android"></div>
<div class="dashicons-icon-hardware-tablet-mac" title="hardware-tablet-mac"></div>
<div class="dashicons-icon-hardware-tv" title="hardware-tv"></div>
<div class="dashicons-icon-hardware-watch" title="hardware-watch"></div>

<div class="dashicons-icon-image-add-to-photos" title="image-add-to-photos"></div>
<div class="dashicons-icon-image-adjust" title="image-adjust"></div>
<div class="dashicons-icon-image-assistant-photo" title="image-assistant-photo"></div>
<div class="dashicons-icon-image-audiotrack" title="image-audiotrack"></div>
<div class="dashicons-icon-image-blur-circular" title="image-blur-circular"></div>
<div class="dashicons-icon-image-blur-linear" title="image-blur-linear"></div>
<div class="dashicons-icon-image-blur-off" title="image-blur-off"></div>
<div class="dashicons-icon-image-blur-on" title="image-blur-on"></div>
<div class="dashicons-icon-image-brightness-1" title="image-brightness-1"></div>
<div class="dashicons-icon-image-brightness-2" title="image-brightness-2"></div>
<div class="dashicons-icon-image-brightness-3" title="image-brightness-3"></div>
<div class="dashicons-icon-image-brightness-4" title="image-brightness-4"></div>
<div class="dashicons-icon-image-brightness-5" title="image-brightness-5"></div>
<div class="dashicons-icon-image-brightness-6" title="image-brightness-6"></div>
<div class="dashicons-icon-image-brightness-7" title="image-brightness-7"></div>
<div class="dashicons-icon-image-brush" title="image-brush"></div>
<div class="dashicons-icon-image-camera" title="image-camera"></div>
<div class="dashicons-icon-image-camera-alt" title="image-camera-alt"></div>
<div class="dashicons-icon-image-camera-front" title="image-camera-front"></div>
<div class="dashicons-icon-image-camera-rear" title="image-camera-rear"></div>
<div class="dashicons-icon-image-camera-roll" title="image-camera-roll"></div>
<div class="dashicons-icon-image-center-focus-strong" title="image-center-focus-strong"></div>
<div class="dashicons-icon-image-center-focus-weak" title="image-center-focus-weak"></div>
<div class="dashicons-icon-image-collections" title="image-collections"></div>
<div class="dashicons-icon-image-color-lens" title="image-color-lens"></div>
<div class="dashicons-icon-image-colorize" title="image-colorize"></div>
<div class="dashicons-icon-image-compare" title="image-compare"></div>
<div class="dashicons-icon-image-control-point" title="image-control-point"></div>
<div class="dashicons-icon-image-control-point-duplicate" title="image-control-point-duplicate"></div>
<div class="dashicons-icon-image-crop-16-9" title="image-crop-16-9"></div>
<div class="dashicons-icon-image-crop" title="image-crop"></div>
<div class="dashicons-icon-image-crop-3-2" title="image-crop-3-2"></div>
<div class="dashicons-icon-image-crop-5-4" title="image-crop-5-4"></div>
<div class="dashicons-icon-image-crop-7-5" title="image-crop-7-5"></div>
<div class="dashicons-icon-image-crop-din" title="image-crop-din"></div>
<div class="dashicons-icon-image-crop-free" title="image-crop-free"></div>
<div class="dashicons-icon-image-crop-landscape" title="image-crop-landscape"></div>
<div class="dashicons-icon-image-crop-original" title="image-crop-original"></div>
<div class="dashicons-icon-image-crop-portrait" title="image-crop-portrait"></div>
<div class="dashicons-icon-image-crop-square" title="image-crop-square"></div>
<div class="dashicons-icon-image-dehaze" title="image-dehaze"></div>
<div class="dashicons-icon-image-details" title="image-details"></div>
<div class="dashicons-icon-image-edit" title="image-edit"></div>
<div class="dashicons-icon-image-exposure" title="image-exposure"></div>
<div class="dashicons-icon-image-exposure-minus-1" title="image-exposure-minus-1"></div>
<div class="dashicons-icon-image-exposure-minus-2" title="image-exposure-minus-2"></div>
<div class="dashicons-icon-image-exposure-plus-1" title="image-exposure-plus-1"></div>
<div class="dashicons-icon-image-exposure-plus-2" title="image-exposure-plus-2"></div>
<div class="dashicons-icon-image-exposure-zero" title="image-exposure-zero"></div>
<div class="dashicons-icon-image-filter-1" title="image-filter-1"></div>
<div class="dashicons-icon-image-filter" title="image-filter"></div>
<div class="dashicons-icon-image-filter-2" title="image-filter-2"></div>
<div class="dashicons-icon-image-filter-3" title="image-filter-3"></div>
<div class="dashicons-icon-image-filter-4" title="image-filter-4"></div>
<div class="dashicons-icon-image-filter-5" title="image-filter-5"></div>
<div class="dashicons-icon-image-filter-6" title="image-filter-6"></div>
<div class="dashicons-icon-image-filter-7" title="image-filter-7"></div>
<div class="dashicons-icon-image-filter-8" title="image-filter-8"></div>
<div class="dashicons-icon-image-filter-9" title="image-filter-9"></div>
<div class="dashicons-icon-image-filter-9-plus" title="image-filter-9-plus"></div>
<div class="dashicons-icon-image-filter-b-and-w" title="image-filter-b-and-w"></div>
<div class="dashicons-icon-image-filter-center-focus" title="image-filter-center-focus"></div>
<div class="dashicons-icon-image-filter-drama" title="image-filter-drama"></div>
<div class="dashicons-icon-image-filter-frames" title="image-filter-frames"></div>
<div class="dashicons-icon-image-filter-hdr" title="image-filter-hdr"></div>
<div class="dashicons-icon-image-filter-none" title="image-filter-none"></div>
<div class="dashicons-icon-image-filter-tilt-shift" title="image-filter-tilt-shift"></div>
<div class="dashicons-icon-image-filter-vintage" title="image-filter-vintage"></div>
<div class="dashicons-icon-image-flare" title="image-flare"></div>
<div class="dashicons-icon-image-flash-auto" title="image-flash-auto"></div>
<div class="dashicons-icon-image-flash-off" title="image-flash-off"></div>
<div class="dashicons-icon-image-flash-on" title="image-flash-on"></div>
<div class="dashicons-icon-image-flip" title="image-flip"></div>
<div class="dashicons-icon-image-gradient" title="image-gradient"></div>
<div class="dashicons-icon-image-grain" title="image-grain"></div>
<div class="dashicons-icon-image-grid-off" title="image-grid-off"></div>
<div class="dashicons-icon-image-grid-on" title="image-grid-on"></div>
<div class="dashicons-icon-image-hdr-off" title="image-hdr-off"></div>
<div class="dashicons-icon-image-hdr-on" title="image-hdr-on"></div>
<div class="dashicons-icon-image-hdr-strong" title="image-hdr-strong"></div>
<div class="dashicons-icon-image-hdr-weak" title="image-hdr-weak"></div>
<div class="dashicons-icon-image-healing" title="image-healing"></div>
<div class="dashicons-icon-image-image" title="image-image"></div>
<div class="dashicons-icon-image-image-aspect-ratio" title="image-image-aspect-ratio"></div>
<div class="dashicons-icon-image-iso" title="image-iso"></div>
<div class="dashicons-icon-image-landscape" title="image-landscape"></div>
<div class="dashicons-icon-image-leak-add" title="image-leak-add"></div>
<div class="dashicons-icon-image-leak-remove" title="image-leak-remove"></div>
<div class="dashicons-icon-image-lens" title="image-lens"></div>
<div class="dashicons-icon-image-looks" title="image-looks"></div>
<div class="dashicons-icon-image-looks-3" title="image-looks-3"></div>
<div class="dashicons-icon-image-looks-4" title="image-looks-4"></div>
<div class="dashicons-icon-image-looks-5" title="image-looks-5"></div>
<div class="dashicons-icon-image-looks-6" title="image-looks-6"></div>
<div class="dashicons-icon-image-looks-one" title="image-looks-one"></div>
<div class="dashicons-icon-image-looks-two" title="image-looks-two"></div>
<div class="dashicons-icon-image-loupe" title="image-loupe"></div>
<div class="dashicons-icon-image-movie-creation" title="image-movie-creation"></div>
<div class="dashicons-icon-image-nature" title="image-nature"></div>
<div class="dashicons-icon-image-nature-people" title="image-nature-people"></div>
<div class="dashicons-icon-image-navigate-before" title="image-navigate-before"></div>
<div class="dashicons-icon-image-navigate-next" title="image-navigate-next"></div>
<div class="dashicons-icon-image-palette" title="image-palette"></div>
<div class="dashicons-icon-image-panorama" title="image-panorama"></div>
<div class="dashicons-icon-image-panorama-fisheye" title="image-panorama-fisheye"></div>
<div class="dashicons-icon-image-panorama-horizontal" title="image-panorama-horizontal"></div>
<div class="dashicons-icon-image-panorama-vertical" title="image-panorama-vertical"></div>
<div class="dashicons-icon-image-panorama-wide-angle" title="image-panorama-wide-angle"></div>
<div class="dashicons-icon-image-photo" title="image-photo"></div>
<div class="dashicons-icon-image-photo-album" title="image-photo-album"></div>
<div class="dashicons-icon-image-photo-camera" title="image-photo-camera"></div>
<div class="dashicons-icon-image-photo-library" title="image-photo-library"></div>
<div class="dashicons-icon-image-portrait" title="image-portrait"></div>
<div class="dashicons-icon-image-remove-red-eye" title="image-remove-red-eye"></div>
<div class="dashicons-icon-image-rotate-left" title="image-rotate-left"></div>
<div class="dashicons-icon-image-rotate-right" title="image-rotate-right"></div>
<div class="dashicons-icon-image-slideshow" title="image-slideshow"></div>
<div class="dashicons-icon-image-straighten" title="image-straighten"></div>
<div class="dashicons-icon-image-style" title="image-style"></div>
<div class="dashicons-icon-image-switch-camera" title="image-switch-camera"></div>
<div class="dashicons-icon-image-switch-video" title="image-switch-video"></div>
<div class="dashicons-icon-image-tag-faces" title="image-tag-faces"></div>
<div class="dashicons-icon-image-texture" title="image-texture"></div>
<div class="dashicons-icon-image-timelapse" title="image-timelapse"></div>
<div class="dashicons-icon-image-timer-10" title="image-timer-10"></div>
<div class="dashicons-icon-image-timer" title="image-timer"></div>
<div class="dashicons-icon-image-timer-3" title="image-timer-3"></div>
<div class="dashicons-icon-image-timer-auto" title="image-timer-auto"></div>
<div class="dashicons-icon-image-timer-off" title="image-timer-off"></div>
<div class="dashicons-icon-image-tonality" title="image-tonality"></div>
<div class="dashicons-icon-image-transform" title="image-transform"></div>
<div class="dashicons-icon-image-tune" title="image-tune"></div>
<div class="dashicons-icon-image-wb-auto" title="image-wb-auto"></div>
<div class="dashicons-icon-image-wb-cloudy" title="image-wb-cloudy"></div>
<div class="dashicons-icon-image-wb-incandescent" title="image-wb-incandescent"></div>
<div class="dashicons-icon-image-wb-irradescent" title="image-wb-irradescent"></div>
<div class="dashicons-icon-image-wb-sunny" title="image-wb-sunny"></div>

<div class="dashicons-icon-maps-beenhere" title="maps-beenhere"></div>
<div class="dashicons-icon-maps-directions" title="maps-directions"></div>
<div class="dashicons-icon-maps-directions-bike" title="maps-directions-bike"></div>
<div class="dashicons-icon-maps-directions-bus" title="maps-directions-bus"></div>
<div class="dashicons-icon-maps-directions-car" title="maps-directions-car"></div>
<div class="dashicons-icon-maps-directions-ferry" title="maps-directions-ferry"></div>
<div class="dashicons-icon-maps-directions-subway" title="maps-directions-subway"></div>
<div class="dashicons-icon-maps-directions-train" title="maps-directions-train"></div>
<div class="dashicons-icon-maps-directions-transit" title="maps-directions-transit"></div>
<div class="dashicons-icon-maps-directions-walk" title="maps-directions-walk"></div>
<div class="dashicons-icon-maps-flight" title="maps-flight"></div>
<div class="dashicons-icon-maps-hotel" title="maps-hotel"></div>
<div class="dashicons-icon-maps-layers" title="maps-layers"></div>
<div class="dashicons-icon-maps-layers-clear" title="maps-layers-clear"></div>
<div class="dashicons-icon-maps-local-airport" title="maps-local-airport"></div>
<div class="dashicons-icon-maps-local-atm" title="maps-local-atm"></div>
<div class="dashicons-icon-maps-local-attraction" title="maps-local-attraction"></div>
<div class="dashicons-icon-maps-local-bar" title="maps-local-bar"></div>
<div class="dashicons-icon-maps-local-cafe" title="maps-local-cafe"></div>
<div class="dashicons-icon-maps-local-car-wash" title="maps-local-car-wash"></div>
<div class="dashicons-icon-maps-local-convenience-store" title="maps-local-convenience-store"></div>
<div class="dashicons-icon-maps-local-drink" title="maps-local-drink"></div>
<div class="dashicons-icon-maps-local-florist" title="maps-local-florist"></div>
<div class="dashicons-icon-maps-local-gas-station" title="maps-local-gas-station"></div>
<div class="dashicons-icon-maps-local-grocery-store" title="maps-local-grocery-store"></div>
<div class="dashicons-icon-maps-local-hospital" title="maps-local-hospital"></div>
<div class="dashicons-icon-maps-local-hotel" title="maps-local-hotel"></div>
<div class="dashicons-icon-maps-local-laundry-service" title="maps-local-laundry-service"></div>
<div class="dashicons-icon-maps-local-library" title="maps-local-library"></div>
<div class="dashicons-icon-maps-local-mall" title="maps-local-mall"></div>
<div class="dashicons-icon-maps-local-movies" title="maps-local-movies"></div>
<div class="dashicons-icon-maps-local-offer" title="maps-local-offer"></div>
<div class="dashicons-icon-maps-local-parking" title="maps-local-parking"></div>
<div class="dashicons-icon-maps-local-pharmacy" title="maps-local-pharmacy"></div>
<div class="dashicons-icon-maps-local-phone" title="maps-local-phone"></div>
<div class="dashicons-icon-maps-local-pizza" title="maps-local-pizza"></div>
<div class="dashicons-icon-maps-local-play" title="maps-local-play"></div>
<div class="dashicons-icon-maps-local-post-office" title="maps-local-post-office"></div>
<div class="dashicons-icon-maps-local-print-shop" title="maps-local-print-shop"></div>
<div class="dashicons-icon-maps-local-restaurant" title="maps-local-restaurant"></div>
<div class="dashicons-icon-maps-local-see" title="maps-local-see"></div>
<div class="dashicons-icon-maps-local-shipping" title="maps-local-shipping"></div>
<div class="dashicons-icon-maps-local-taxi" title="maps-local-taxi"></div>
<div class="dashicons-icon-maps-location-history" title="maps-location-history"></div>
<div class="dashicons-icon-maps-map" title="maps-map"></div>
<div class="dashicons-icon-maps-my-location" title="maps-my-location"></div>
<div class="dashicons-icon-maps-navigation" title="maps-navigation"></div>
<div class="dashicons-icon-maps-pin-drop" title="maps-pin-drop"></div>
<div class="dashicons-icon-maps-place" title="maps-place"></div>
<div class="dashicons-icon-maps-rate-review" title="maps-rate-review"></div>
<div class="dashicons-icon-maps-restaurant-menu" title="maps-restaurant-menu"></div>
<div class="dashicons-icon-maps-satellite" title="maps-satellite"></div>
<div class="dashicons-icon-maps-store-mall-directory" title="maps-store-mall-directory"></div>
<div class="dashicons-icon-maps-terrain" title="maps-terrain"></div>
<div class="dashicons-icon-maps-traffic" title="maps-traffic"></div>

<div class="dashicons-icon-navigation-apps" title="navigation-apps"></div>
<div class="dashicons-icon-navigation-arrow-back" title="navigation-arrow-back"></div>
<div class="dashicons-icon-navigation-arrow-drop-down" title="navigation-arrow-drop-down"></div>
<div class="dashicons-icon-navigation-arrow-drop-down-circle" title="navigation-arrow-drop-down-circle"></div>
<div class="dashicons-icon-navigation-arrow-drop-up" title="navigation-arrow-drop-up"></div>
<div class="dashicons-icon-navigation-arrow-forward" title="navigation-arrow-forward"></div>
<div class="dashicons-icon-navigation-cancel" title="navigation-cancel"></div>
<div class="dashicons-icon-navigation-check" title="navigation-check"></div>
<div class="dashicons-icon-navigation-chevron-left" title="navigation-chevron-left"></div>
<div class="dashicons-icon-navigation-chevron-right" title="navigation-chevron-right"></div>
<div class="dashicons-icon-navigation-close" title="navigation-close"></div>
<div class="dashicons-icon-navigation-expand-less" title="navigation-expand-less"></div>
<div class="dashicons-icon-navigation-expand-more" title="navigation-expand-more"></div>
<div class="dashicons-icon-navigation-fullscreen" title="navigation-fullscreen"></div>
<div class="dashicons-icon-navigation-fullscreen-exit" title="navigation-fullscreen-exit"></div>
<div class="dashicons-icon-navigation-menu" title="navigation-menu"></div>
<div class="dashicons-icon-navigation-more-horiz" title="navigation-more-horiz"></div>
<div class="dashicons-icon-navigation-more-vert" title="navigation-more-vert"></div>
<div class="dashicons-icon-navigation-refresh" title="navigation-refresh"></div>
<div class="dashicons-icon-navigation-unfold-less" title="navigation-unfold-less"></div>
<div class="dashicons-icon-navigation-unfold-more" title="navigation-unfold-more"></div>

<div class="dashicons-icon-notification-adb" title="notification-adb"></div>
<div class="dashicons-icon-notification-bluetooth-audio" title="notification-bluetooth-audio"></div>
<div class="dashicons-icon-notification-disc-full" title="notification-disc-full"></div>
<div class="dashicons-icon-notification-dnd-forwardslash" title="notification-dnd-forwardslash"></div>
<div class="dashicons-icon-notification-do-not-disturb" title="notification-do-not-disturb"></div>
<div class="dashicons-icon-notification-drive-eta" title="notification-drive-eta"></div>
<div class="dashicons-icon-notification-event-available" title="notification-event-available"></div>
<div class="dashicons-icon-notification-event-busy" title="notification-event-busy"></div>
<div class="dashicons-icon-notification-event-note" title="notification-event-note"></div>
<div class="dashicons-icon-notification-folder-special" title="notification-folder-special"></div>
<div class="dashicons-icon-notification-mms" title="notification-mms"></div>
<div class="dashicons-icon-notification-more" title="notification-more"></div>
<div class="dashicons-icon-notification-network-locked" title="notification-network-locked"></div>
<div class="dashicons-icon-notification-phone-bluetooth-speaker" title="notification-phone-bluetooth-speaker"></div>
<div class="dashicons-icon-notification-phone-forwarded" title="notification-phone-forwarded"></div>
<div class="dashicons-icon-notification-phone-in-talk" title="notification-phone-in-talk"></div>
<div class="dashicons-icon-notification-phone-locked" title="notification-phone-locked"></div>
<div class="dashicons-icon-notification-phone-missed" title="notification-phone-missed"></div>
<div class="dashicons-icon-notification-phone-paused" title="notification-phone-paused"></div>
<div class="dashicons-icon-notification-play-download" title="notification-play-download"></div>
<div class="dashicons-icon-notification-play-install" title="notification-play-install"></div>
<div class="dashicons-icon-notification-sd-card" title="notification-sd-card"></div>
<div class="dashicons-icon-notification-sim-card-alert" title="notification-sim-card-alert"></div>
<div class="dashicons-icon-notification-sms" title="notification-sms"></div>
<div class="dashicons-icon-notification-sms-failed" title="notification-sms-failed"></div>
<div class="dashicons-icon-notification-sync" title="notification-sync"></div>
<div class="dashicons-icon-notification-sync-disabled" title="notification-sync-disabled"></div>
<div class="dashicons-icon-notification-sync-problem" title="notification-sync-problem"></div>
<div class="dashicons-icon-notification-system-update" title="notification-system-update"></div>
<div class="dashicons-icon-notification-tap-and-play" title="notification-tap-and-play"></div>
<div class="dashicons-icon-notification-time-to-leave" title="notification-time-to-leave"></div>
<div class="dashicons-icon-notification-vibration" title="notification-vibration"></div>
<div class="dashicons-icon-notification-voice-chat" title="notification-voice-chat"></div>
<div class="dashicons-icon-notification-vpn-lock" title="notification-vpn-lock"></div>

<div class="dashicons-icon-social-cake" title="social-cake"></div>
<div class="dashicons-icon-social-domain" title="social-domain"></div>
<div class="dashicons-icon-social-group" title="social-group"></div>
<div class="dashicons-icon-social-group-add" title="social-group-add"></div>
<div class="dashicons-icon-social-location-city" title="social-location-city"></div>
<div class="dashicons-icon-social-mood" title="social-mood"></div>
<div class="dashicons-icon-social-notifications" title="social-notifications"></div>
<div class="dashicons-icon-social-notifications-none" title="social-notifications-none"></div>
<div class="dashicons-icon-social-notifications-off" title="social-notifications-off"></div>
<div class="dashicons-icon-social-notifications-on" title="social-notifications-on"></div>
<div class="dashicons-icon-social-notifications-paused" title="social-notifications-paused"></div>
<div class="dashicons-icon-social-pages" title="social-pages"></div>
<div class="dashicons-icon-social-party-mode" title="social-party-mode"></div>
<div class="dashicons-icon-social-people" title="social-people"></div>
<div class="dashicons-icon-social-people-outline" title="social-people-outline"></div>
<div class="dashicons-icon-social-person" title="social-person"></div>
<div class="dashicons-icon-social-person-add" title="social-person-add"></div>
<div class="dashicons-icon-social-person-outline" title="social-person-outline"></div>
<div class="dashicons-icon-social-plus-one" title="social-plus-one"></div>
<div class="dashicons-icon-social-poll" title="social-poll"></div>
<div class="dashicons-icon-social-public" title="social-public"></div>
<div class="dashicons-icon-social-school" title="social-school"></div>
<div class="dashicons-icon-social-share" title="social-share"></div>
<div class="dashicons-icon-social-whatshot" title="social-whatshot"></div>

<div class="dashicons-icon-toggle-check-box" title="toggle-check-box"></div>
<div class="dashicons-icon-toggle-check-box-outline-blank" title="toggle-check-box-outline-blank"></div>
<div class="dashicons-icon-toggle-radio-button-off" title="toggle-radio-button-off"></div>
<div class="dashicons-icon-toggle-radio-button-on" title="toggle-radio-button-on"></div>
